import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Container from "@/components/layout/Container";
import Navbar from "@/components/layout/Navbar";
import ReduxProvider from "./redux/ReduxProvider";
import UserProvider from "@/components/providers/UserProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <ReduxProvider>

          {/* PROVIDERS */}
          {/* Used to fetch data on page-load */}
          <UserProvider />
          <div className="wrapper">
            <Container className="w-full">
              <Navbar />
            </Container>
          </div>
          {children}
        </ReduxProvider>

      </body>
    </html>
  );
}
