
import '@once-ui-system/core/css/styles.css';
import '@once-ui-system/core/css/tokens.css';

import "../styles/globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { DataThemeProvider, IconProvider, LayoutProvider, ThemeProvider, ThemeSwitcher, ToastProvider } from "@once-ui-system/core";
import ReduxProvider from './redux/ReduxProvider';
import Navbar from '@/components/layout/Navbar';
import { Metadata } from 'next';
import UserProvider from '@/components/providers/UserProvider';
import Container from '@/components/layout/Container';

interface RootLayoutProps {
  children: React.ReactNode;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Seagull",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} antialiased
        `}
      >
        <LayoutProvider>
            <DataThemeProvider>
              <ThemeProvider
                theme="system" // system | dark | light
                accent="green" // blue | indigo | violet | magenta | pink | red | orange | yellow | moss | green | emerald | aqua | cyan
                neutral="gray" // sand | gray | slate
                solid="contrast" // color | contrast
                solidStyle="flat" // flat | plastic
                surface="translucent" // filled | translucent
                transition="all"
                border="conservative"
              >
                <ToastProvider>

                <ReduxProvider>

                  {/* USED TO FETCH USER */}
                  <UserProvider />

                  <Container className='w-full mt-5'>
                    <Navbar />
                  </Container>
                  {children}

                </ReduxProvider>

              </ToastProvider>
            </ThemeProvider>
          </DataThemeProvider>
        </LayoutProvider>
      </body>
    </html>
  );
}
